Write a small piece of code to explain broadcasting in numpy.

Broadcasting is a feature in Numpy that allows the user to perform various operations between arrays of different shapes and size. Let us see 2 basic examples:

In [1]:
import numpy as np

In [6]:
a = np.array([[3,7,8],[9,5,6],[2,4,1]])
b = np.array([[10,20,30]])

z= a+b

print("The original matrix is ")
print(a)
print("The new matrix is ")
print(z)

The original matrix is 
[[3 7 8]
 [9 5 6]
 [2 4 1]]
The new matrix is 
[[13 27 38]
 [19 25 36]
 [12 24 31]]


We can see that even though the size were different with the help of broadcasting each row in a was added with the values of b.

In [5]:
#This even works with multiplication
a = np.array([[3,7,8],[9,5,6],[2,4,1]])
b = 2

z = a*b

print("The original matrix is ")
print(a)
print("The new matrix is ")
print(z)

The original matrix is 
[[3 7 8]
 [9 5 6]
 [2 4 1]]
The new matrix is 
[[ 6 14 16]
 [18 10 12]
 [ 4  8  2]]


We can see that even though the size were different with the help of broadcasting each element was multiplied with the value of b.