Write Python code to multiply the above two matrices. 
Solve using list of lists and then use numpy. 
Compare the timing of both solutions. Which one is faster? Why?

In [1]:
#Let us take 2 matrix of size 3x3 named A and B. Also there multiplication is named as AxB for list of list method
import time
import numpy as np

In [2]:
start = time.time()
A = [[3,7,8],[9,5,6],[2,4,1]]
B = [[13,17,18],[19,15,16],[12,14,11]]
AxB = [[0,0,0],[0,0,0],[0,0,0]]

In [3]:
ar = len(A)
ac = len(A[0])
br = len(B)
bc = len(B[0])

In [4]:
if (ac==br):
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                AxB[i][j] += A[i][k] * B[k][j]
    for g in AxB:
        print(g)
else:
    print("Matrix Multiplication AxB not possible")
end = time.time()

print("Time Taken by the list of list method = ",end - start)

[268, 268, 254]
[284, 312, 308]
[114, 108, 111]
Time Taken by the list of list method =  0.019999980926513672


In [5]:
#Let us take 2 matrix of size 3x3 named P and Q. Also there multiplication is named as PxQ for numpy method

In [6]:
start = time.time()
P = [[3,7,8],[9,5,6],[2,4,1]]
Q = [[13,17,18],[19,15,16],[12,14,11]]

In [7]:
PxQ = np.dot(P,Q)
for g in PxQ:
    print(g)
end = time.time()
print("Time Taken by the numpy method = ",end - start)

[268 268 254]
[284 312 308]
[114 108 111]
Time Taken by the numpy method =  0.006999969482421875


From the above part we can clearly see that the time taken by the numpy method is very less compared to the list of list method.
1) This is because Numpy makes use of fragmentation i.e. it divided the task into fragments and then runs all the fragments simultaneously
2) Also Numpy makes use of lanuguages such as C, C++ and Fortan which has a very less execution time compared to Python